# Generated by Django 3.2.4 on 2021-10-15 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='basliq:')),
                ('content', models.TextField(verbose_name='mezmun:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='yaradilma tarixi:')),
                ('confirm', models.BooleanField(default=False, verbose_name='tamamlanilib?:')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='yaradilma tarixi:')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='tasklar:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi:')),
            ],
        ),
    ]
