# Generated by Django 3.2.4 on 2021-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211015_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='tamamlanilib?:'),
        ),
    ]
